#include "zinc_ui.h"

const char *zinc_help_text = 
"Pattern:\n"
"  for Linux & Mac:\n"
"    ./zinc [Options] [Image]\n"
"  for Windows:\n"
"    zinc [Options] [Image]\n\n"

"Note:\n"
"  You have to give the parameters after function call.\n"
"  You neigther have to put <> brackets nor commas when <r,g,b> or <x,y> is specified. Just put values and spaces between the parameters.\n"
"    Example: 124 23 53 (r,g,b example)\n"
"             425 645   (x,y example).\n"
"  Lastly we use factors instead of percentages. As it\'s more accurate. Factors range from 0.0 to 1.0\n\n"

"Options:\n"
"  --version                                    check the version of zinc.\n"
"  --help                                       show this help message.\n"
"  --gray                                       turn an image gray.\n"
"  --gray-lumin                                 turn the image gray with rgb values that fits human eyes.\n"
"  --gray-light                                 turn the image gray with min,max values.\n"
"  --tint <r,g,b>                               tint the image with the <r,g,b> values.\n"
"  --brightness <factor>                        change the brightness depending on the percentage.\n"
"  --invert                                     invert the colors of the image.\n"
"  --cropwctr <x1,y1> <x2,y2> <r,g,b>           crop the image without changing the resolution. x1,y1 = top left coordinate. x2,y2 = bottom right coordinate. r,g,b = color for the uncropped areas.\n"
"  --cropctr <x1,y1> <x2,y2>                    crop the image and change the resolution. x1,y1 = top left coordinate. x2,y2 = bottom right coordinate.\n"
"  more soon...\n\n"

"Short forms:\n"
"  --version        ->     -v\n"
"  --help           ->     -h\n"
"  --gray           ->     -g\n"
"  --gray-lumin     ->     -gl\n"
"  --gray-light     ->     -gli\n"
"  --tint           ->     -ti\n"
"  --brightness     ->     -br\n"
"  --invert         ->     -in\n"
"  --cropwctr       ->     -cwctr\n"
"  --cropctr        ->     -cctr\n"
"  more soon...\n";
