#include "zinc_global.h"

const char *zinc_help_text =
"Pattern:\n"
"  for Linux & Mac:\n"
"    ./zinc [Options] [Image]\n"
"  for Windows:\n"
"    zinc [Options] [Image]\n\n"

"Note:\n"
"  You have to give the parameters after function call.\n"
"  You neigther have to put <> brackets nor commas when <r,g,b> or <x,y> is specified. Just put values and spaces between the parameters.\n"
"    Example: 0.43 0.654 0.12 (r,g,b example)\n"
"             425 645   (x,y example).\n"
"  Lastly we use factors instead of percentages. As it\'s more accurate.\n"
"    Example: for brightness, setting factor to 2.0 will double the brightness.\n"
"             for tinting, changing the r value to 1.5 will increase half of the red value.\n\n"

"Options:\n"
"  -v, --version                                    check the version of zinc.\n"
"  -h, --help                                       show this help message.\n"
"  -o, --output                                     choose a name for the output file.\n"
"  -g, --gray                                       turn an image gray.\n"
"  -gl, --gray-lumin                                turn the image gray with rgb values that fits human eyes.\n"
"  -gli, --gray-light                               turn the image gray with min,max values.\n"
"  -ti, --tint <r,g,b>                              tint the image with the <r,g,b> values.\n"
"  -br, --brightness <factor>                       change the brightness depending on the percentage.\n"
"  -in --invert                                     invert the colors of the image.\n"
"  -cwctr, --cropwctr <x1,y1> <x2,y2> <r,g,b>       crop the image without changing the resolution. x1,y1 = top left coordinate. x2,y2 = bottom right coordinate. r,g,b = color for the uncropped areas.\n"
"  -cctr, --cropctr <x1,y1> <x2,y2>                 crop the image and change the resolution. x1,y1 = top left coordinate. x2,y2 = bottom right coordinate.\n"
"  -th, --threshold <intensity>                     turns the image black and white depending on the threshold.\n"
"  more soon...\n\n";
